# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Flutter action
      uses: subosito/flutter-action@master
      with:
        channel: 'dev'
    - run: flutter config --enable-web
    - run: flutter build web

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: build/web
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - run: flutter build apk

    - uses: actions/upload-artifact@v1
      with:
        name: Build
        path: build/app/outputs/flutter-apk/app-release.apk
